name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:

  fypp:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '>=3.5'

      - name: Verify python installation
        run: python3 -V

      - name: Install fypp
        run: pip install --upgrade fypp ninja

      - name: Verify fypp installation
        run: fypp --version

      - name: Run fypp
        run: |
          cd src
          chmod +x ./run_fypp.sh
          ./run_fypp.sh
          cd ../test
          chmod +x ./run_fypp.sh
          ./run_fypp.sh
          cd ..

      - name: Upload artifacts (src)
        uses: actions/upload-artifact@v4
        with:
          name: src-f90
          path: src/*.f90
          retention-days: 1

      - name: Upload artifacts (test)
        uses: actions/upload-artifact@v4
        with:
          name: test-f90
          path: test/*.f90
          retention-days: 1

  test:

    needs: fypp

    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [debug, release]

    steps:

      - uses: actions/checkout@v5

      - name: Get .f90 files generated by fypp (src)
        uses: actions/download-artifact@v4
        with:
          name: src-f90
          path: src-f90

      - name: Get .f90 files generated by fypp (test)
        uses: actions/download-artifact@v4
        with:
          name: test-f90
          path: test-f90

      - name: Copy .f90 files generated by fypp
        run: |
          cp ./src-f90/*.f90 ./src
          cp ./test-f90/*.f90 ./test

      - name: Check the .f90 files generated by fypp
        run: |
          cd src
          ls -a
          cd ../test
          ls -a
          cd ..

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify fpm installation
        run: fpm --version

      - name: Build library using fpm
        run: fpm build --profile ${{ matrix.profile }}

      - name: Test library using fpm (${{ matrix.profile }} mode)
        run: fpm test --profile ${{ matrix.profile }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: check-${{ matrix.profile }}
          path: check*.md
          retention-days: 1

  ford:

    needs: test

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5

      - name: Verify python installation
        run: python3 -V

      - name: Install FORD
        run: sudo pip install ford

      - name: Verify FORD installation
        run: ford --version

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Verify Graphviz installation
        run: dot -V
